"""Closed geodesics of a doubled geodesic polygon, and the hyperbolic term of the
Selberg trace formula they produce.

Setting.  Let P be a compact convex geodesic polygon in H^2 with angles pi/m_i,
W the group generated by the reflections in its sides (P is a fundamental domain
of W), and Gamma the index-2 subgroup of orientation-preserving elements.  The
double of P is the orbifold Gamma\\H^2, and P u sP is a fundamental domain of
Gamma for any side reflection s.

Hyperbolic term (Dryden-Strohmaier eq. (1), h(r) = exp(-t(1/4 + r^2)),
g(u) = (1/2pi) int h(r) e^{-iru} dr = e^{-t/4} e^{-u^2/4t} / sqrt(4 pi t)):

    H(t) = sum_{[gamma] hyperbolic} l(gamma_0) / (2 sinh(l(gamma)/2)) * g(l(gamma)).

Conjugacy classes are never identified explicitly.  For a hyperbolic gamma with
centraliser <gamma_0>, the axes of the conjugates h gamma h^-1 (h in Gamma/<gamma_0>)
cut a fundamental domain F of Gamma in segments whose lengths add up to the
length of axis/<gamma_0>, which is l(gamma_0).  Hence

    H(t) = sum_{gamma in Gamma hyperbolic} len(axis(gamma) n F) * G_t(l(gamma)),
    G_t(l) = g(l) / (2 sinh(l/2)).

With F = P u sP, and gamma -> s gamma s a bijection of the hyperbolic elements
carrying axis(gamma) n sP to axis(s gamma s) n P,

    H(t) = 2 sum_{gamma in Gamma hyperbolic} len(axis(gamma) n P) * G_t(l(gamma)).      (*)

A segment of an axis lying ON a side of P is shared by two tiles and is counted
with weight 1/2.

Enumeration.  Work in the hyperboloid model (form -x0^2 + x1^2 + x2^2, base point
o = (1,0,0) = the origin of the disk).  If axis(gamma) meets P then
d(o, gamma o) <= l(gamma) + 2 r_P, r_P = max_{y in P} d(o, y).  Tiles wP are
visited breadth-first through side adjacency (wP and w s_i P share a side); a
tile met by the geodesic segment from o to gamma o has d(o, w o) <= d(o, gamma o)
+ r_P, so pruning at d(o, w o) > l_max + 3 r_P loses nothing.

Output: the weighted length spectrum, a list of (l, w) with w = 2 len(axis n P)
summed over the elements of length l (equal lengths merged at 1e-9).  For a
primitive length, w = l * (number of oriented primitive closed geodesics of that
length); the integrality of w/l is asserted for the shortest lengths.
"""

import numpy as np

J = np.diag([-1.0, 1.0, 1.0])


def lorentz(u, v):
    return -u[0] * v[0] + u[1] * v[1] + u[2] * v[2]


def disk_to_hyp(z):
    r2 = abs(z) ** 2
    return np.array([1 + r2, 2 * z.real, 2 * z.imag]) / (1 - r2)


def hyp_to_klein(X):
    return np.array([X[1] / X[0], X[2] / X[0]])


def klein_to_hyp(k):
    s = 1 / np.sqrt(1 - k[0] ** 2 - k[1] ** 2)
    return np.array([s, s * k[0], s * k[1]])


def reflection_from_circle(c, r):
    """Lorentz reflection in the geodesic that is the circle |z - c| = r
    (orthogonal to |z| = 1) in the Poincare disk."""
    c = complex(c)
    # ideal endpoints: |z| = 1 and |z - c| = r  ->  Re(z conj c) = (1 + |c|^2 - r^2)/2 = 1
    # (since |c|^2 = 1 + r^2), so z = (c / |c|^2)(1 +- i r) has |z| = 1
    e1 = c / abs(c) ** 2 * (1 + 1j * r)
    e2 = c / abs(c) ** 2 * (1 - 1j * r)
    N1 = np.array([1.0, e1.real, e1.imag])
    N2 = np.array([1.0, e2.real, e2.imag])
    n = J @ np.cross(N1, N2)
    n = n / np.sqrt(lorentz(n, n))
    return np.eye(3) - 2 * np.outer(n, J @ n), n


def reflection_from_line_through_origin(direction):
    """Reflection in the diameter of the disk with the given unit direction."""
    d = complex(direction) / abs(direction)
    n = np.array([0.0, -d.imag, d.real])
    return np.eye(3) - 2 * np.outer(n, J @ n), n


class Polygon:
    """Convex geodesic polygon: vertices (disk, counter-clockwise) and side
    reflections (side i joins vertex i to vertex i+1)."""

    def __init__(self, vertices_disk, reflections):
        self.vd = [complex(v) for v in vertices_disk]
        self.R = [R for R, _ in reflections]
        self.normals = [n for _, n in reflections]
        self.vk = np.array([hyp_to_klein(disk_to_hyp(v)) for v in self.vd])   # Klein vertices
        o = np.array([1.0, 0, 0])
        # interior base point for tile identification: Klein centroid of the vertices
        self.x0 = klein_to_hyp(self.vk.mean(axis=0))
        self.x0_dist_to_boundary = min(np.arcsinh(abs(lorentz(n, self.x0))) for n in self.normals)
        assert self.x0_dist_to_boundary > 1e-3
        self.r_P = max(np.arccosh(max(-lorentz(o, disk_to_hyp(v)), 1.0)) for v in self.vd)
        for R in self.R:
            assert np.allclose(R @ R, np.eye(3), atol=1e-12)
            assert np.allclose(R.T @ J @ R, J, atol=1e-12)
        # each side's two vertices lie on its mirror
        n = len(self.vd)
        for i in range(n):
            for v in (self.vd[i], self.vd[(i + 1) % n]):
                assert abs(lorentz(self.normals[i], disk_to_hyp(v))) < 1e-9 * (1 + np.abs(disk_to_hyp(v)).max())

    def chord_length(self, A, B):
        """Hyperbolic length of (line through Klein points A, B) n P, with weight 1/2
        if the chord lies on a side of P."""
        d = B - A
        tlo, thi = -np.inf, np.inf
        n = len(self.vk)
        cen = self.vk.mean(axis=0)
        for i in range(n):
            p, q = self.vk[i], self.vk[(i + 1) % n]
            e = q - p
            nor = np.array([e[1], -e[0]])
            if nor @ (cen - p) < 0:
                nor = -nor                 # inward normal
            den = nor @ d
            num = nor @ (A - p)
            if abs(den) < 1e-14:
                if num < -1e-12:
                    return 0.0, False
                continue
            tt = -num / den
            if den > 0:
                tlo = max(tlo, tt)
            else:
                thi = min(thi, tt)
        if not thi > tlo + 1e-13:
            return 0.0, False
        X1, X2 = klein_to_hyp(A + tlo * d), klein_to_hyp(A + thi * d)
        L = float(np.arccosh(max(-lorentz(X1, X2), 1.0)))
        mid = A + 0.5 * (tlo + thi) * d
        on_side = False
        for i in range(n):
            p, q = self.vk[i], self.vk[(i + 1) % n]
            e = q - p
            if abs(e[0] * (mid - p)[1] - e[1] * (mid - p)[0]) / np.linalg.norm(e) < 1e-10:
                on_side = True
        return (0.5 * L if on_side else L), on_side


def axis_klein(g):
    """Ideal endpoints (Klein = Poincare on the circle) of the axis of a hyperbolic
    g in SO+(2,1): its eigenvectors for the eigenvalues e^{+-l} are null."""
    w, V = np.linalg.eig(g)
    idx = np.argsort(np.abs(w))
    ends = []
    for k in (idx[0], idx[-1]):
        v = np.real(V[:, k])
        v = v / v[0]
        ends.append(np.array([v[1], v[2]]))
    return ends


def length_spectrum(poly, l_max, max_tiles=5_000_000):
    """Weighted length spectrum of the doubled polygon up to l_max: sorted list of
    (l, w), w = sum over hyperbolic gamma of length l of 2 len(axis n P)."""
    R_prune = l_max + 3 * poly.r_P
    cosh_prune = np.cosh(R_prune)
    cosh_keep = np.cosh(l_max + 2 * poly.r_P)
    start = np.eye(3)
    # Tile identity = the image of a fixed interior point x0 (W acts freely on the
    # interior of P).  Images of x0 under distinct elements are >= 2 dist(x0, dP)
    # apart hyperbolically, hence at least that far apart in the Euclidean norm of
    # R^3 (|y - y'|_E >= 2 sinh(d/2) on the hyperboloid); two words for the same
    # element differ only by round-off.  So: spatial hash with cell CELL, and a
    # point is "seen" if a stored point within TOL (Euclidean, R^3) exists in one
    # of the 27 neighbouring cells.  TOL << separation, TOL >> round-off.
    x0 = poly.x0
    sep = 2 * poly.x0_dist_to_boundary
    CELL = sep / 4
    TOL = sep / 100
    grid = {}

    def seen_or_add(y):
        c = tuple(np.floor(y / CELL).astype(np.int64))
        for dx in (-1, 0, 1):
            for dy in (-1, 0, 1):
                for dz in (-1, 0, 1):
                    for q in grid.get((c[0] + dx, c[1] + dy, c[2] + dz), ()):
                        if abs(q[0] - y[0]) + abs(q[1] - y[1]) + abs(q[2] - y[2]) < TOL:
                            return True
        grid.setdefault(c, []).append(y)
        return False

    seen_or_add(start @ x0)
    frontier = [(start, 0)]
    records = []
    ntiles = 1
    while frontier:
        new = []
        for g, parity in frontier:
            for R in poly.R:
                h = g @ R
                if h[0, 0] > cosh_prune:
                    continue
                if seen_or_add(h @ x0):
                    continue
                ntiles += 1
                p = 1 - parity
                new.append((h, p))
                if p == 0 and h[0, 0] <= cosh_keep:
                    tr = np.trace(h)
                    if tr > 3 + 1e-9:
                        l = float(np.arccosh((tr - 1) / 2))
                        if l <= l_max:
                            A, B = axis_klein(h)
                            L, _ = poly.chord_length(A, B)
                            if L > 0:
                                records.append((l, 2 * L))
        if ntiles > max_tiles:
            raise RuntimeError(f"tile budget exceeded ({ntiles})")
        frontier = new
    records.sort()
    merged = []
    for l, w in records:
        if merged and abs(l - merged[-1][0]) < 1e-9 * max(1, l):
            merged[-1][1] += w
        else:
            merged.append([l, w])
    return [(l, w) for l, w in merged], ntiles


def hyperbolic_term(spectrum, t):
    """(*) for an array of t: sum_l w(l) e^{-t/4} e^{-l^2/4t} / (sqrt(4 pi t) 2 sinh(l/2))."""
    t = np.atleast_1d(np.asarray(t, dtype=float))
    out = np.zeros_like(t)
    for l, w in spectrum:
        out += w / (2 * np.sinh(l / 2)) * np.exp(-t / 4 - l * l / (4 * t)) / np.sqrt(4 * np.pi * t)
    return out


def tail_bound(spectrum, l_max, area, t):
    """Upper bound for the part of (*) from lengths > l_max, from the count of
    hyperbolic elements with axis meeting P implied by the enumeration's own growth:
    sum of w over lengths in (l, l + 1] <= Cgrowth e^{l}, Cgrowth fitted as the max of
    W(l)/e^l over the enumerated range (a conservative extrapolation, stated as such)."""
    ls = np.array([l for l, _ in spectrum])
    ws = np.array([w for _, w in spectrum])
    cum = np.cumsum(ws)
    Cg = float(np.max(cum / np.exp(ls)))
    t = np.atleast_1d(np.asarray(t, dtype=float))
    out = np.zeros_like(t)
    for k in range(200):
        lo = l_max + k
        out += Cg * np.exp(lo + 1) * np.exp(-t / 4 - lo * lo / (4 * t)) / (np.sqrt(4 * np.pi * t) * 2 * np.sinh(lo / 2))
    return out, Cg


# ---------------------------------------------------------------- polygons
def quad_polygon(lam):
    """The quadrilateral Q of a quad.Lambert instance."""
    vs = lam.quad_vertices()             # V, -conj V, -V, conj V  (ccw)
    sides = lam.quad_sides()             # east, north, west, south
    # side i joins vertex i to vertex i+1: V -> -conj V is the north side, etc.
    order = [1, 2, 3, 0]                 # north, west, south, east
    refl = [reflection_from_circle(complex(sides[k][0]), float(sides[k][1])) for k in order]
    return Polygon([complex(v) for v in vs], refl)


def triangle_polygon(pqr):
    """The S3 triangle (numerics/geometry.py placement): A = 0, B on the positive
    real axis, C on the ray arg z = pi/p; sides AB, BC (arc), CA."""
    import os
    import sys
    sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
    from geometry import Triangle
    T = Triangle(*pqr)
    A, B, C = complex(T.A), complex(T.B), complex(T.C)
    refl = [reflection_from_line_through_origin(1.0 + 0j),
            reflection_from_circle(complex(T.z0), float(T.rho)),
            reflection_from_line_through_origin(C / abs(C))]
    return Polygon([A, B, C], refl)
