#!/usr/bin/env python3
"""
Generate the manuscript's two tables as self-contained LaTeX fragments.

Written to paper/tables/:

    table1.tex  -- cumulative degeneracy counts at the checkpoints
                   (the manuscript's Table 1, \\label{tab:density})
    table2.tex  -- every hyperbolic triad with 10 <= S_1 <= 18 and its exact
                   reciprocal sum, collisions flagged
                   (the manuscript's Table 2, \\label{tab:enum})

Each fragment is a complete float environment, so `\\input{tables/table2}` drops
it in whole and the column count is internal to the fragment.

The collision rows in table2.tex are DETECTED, never hardcoded: a triad is
marked `collision` exactly when its signature group at that sum has more than
one member. If the detection finds no collision at S = 18, that is a failure
and this script raises rather than emit a table with a hand-written row.

Numbers are computed exactly. Decimal ratios are rendered from Fraction values
by integer arithmetic -- see `format_decimal` -- so no float enters even the
presentation layer.

This script does not modify paper/main.tex.
"""

from __future__ import annotations

import sys
from fractions import Fraction
from pathlib import Path
from typing import Sequence

from enumerate_degeneracies import (
    CHECKPOINTS,
    S_MIN,
    degeneracy_groups,
    sweep,
)
from orbifold_enum import enumerate_by_sum, signature

REPO = Path(__file__).resolve().parent.parent
TABLES_DIR = REPO / "paper" / "tables"

ENUM_LO, ENUM_HI = 10, 18
CHECKPOINT_SUMS = [18] + sorted(CHECKPOINTS)


# --------------------------------------------------------------------------
# Exact decimal rendering -- no float anywhere
# --------------------------------------------------------------------------

def format_decimal(value: Fraction, places: int) -> str:
    """
    Render an exact Fraction to `places` decimals, rounding half away from
    zero, using integer arithmetic only.
    """
    if places < 0:
        raise ValueError("places must be >= 0")
    sign = "-" if value < 0 else ""
    value = abs(value)
    scale = 10 ** places
    scaled = value * scale
    # round half away from zero on an exact rational
    whole = scaled.numerator // scaled.denominator
    remainder = scaled - whole
    if remainder * 2 >= 1:
        whole += 1
    if places == 0:
        return f"{sign}{whole}"
    digits = str(whole).rjust(places + 1, "0")
    return f"{sign}{digits[:-places]}.{digits[-places:]}"


def latex_fraction(value: Fraction) -> str:
    """A rational as the manuscript prints it: $a/b$, or $a$ when integral."""
    if value.denominator == 1:
        return f"${value.numerator}$"
    return f"${value.numerator}/{value.denominator}$"


# --------------------------------------------------------------------------
# Table 2 -- tab:enum, the triad enumeration
# --------------------------------------------------------------------------

def collect_enum_rows(lo: int = ENUM_LO, hi: int = ENUM_HI) -> list[tuple[int, tuple[int, ...], Fraction, str]]:
    """
    Every hyperbolic triad with lo <= S_1 <= hi, with its exact R and a status
    of 'unique' or 'collision', the status DETECTED from the signature groups.
    """
    rows: list[tuple[int, tuple[int, ...], Fraction, str]] = []
    total_collisions = 0

    for S in range(lo, hi + 1):
        colliding: set[tuple[int, ...]] = set()
        for group in degeneracy_groups(S):
            colliding.update(group.triples)
        total_collisions += len(colliding)

        triads = list(enumerate_by_sum(3, S))
        if not triads:
            raise RuntimeError(
                f"no hyperbolic triads at S = {S}; the enumerator is broken"
            )
        for orders in triads:
            _, num, den = signature(orders)
            status = "collision" if orders in colliding else "unique"
            rows.append((S, orders, Fraction(num, den), status))

    if total_collisions == 0:
        raise RuntimeError(
            f"no collision detected anywhere in {lo} <= S_1 <= {hi}. "
            "The manuscript's Theorem B requires one at S_1 = 18. Refusing to "
            "emit a table with a hand-written collision row."
        )
    return rows


def render_table2(rows: Sequence[tuple[int, tuple[int, ...], Fraction, str]]) -> str:
    out: list[str] = []
    A = out.append

    A("% Table 2 (tab:enum) -- generated by code/make_table.py. Do not edit by hand.")
    A("% Exact-arithmetic enumeration of all hyperbolic triads with 10 <= S_1 <= 18.")
    A("% Collision rows are detected from the signature (S_1, R), not hardcoded.")
    A(r"\begin{longtable}{cccc}")
    A(r"\caption{Exact-arithmetic cross-check of Theorem~\ref{thm:separation}: all "
      r"hyperbolic triads with $S_1\in[10,18]$ and their reciprocal sums $R$. The only "
      r"coincidence of $R$ within a fixed sum is the boldface pair at $S_1=18$.}"
      r"\label{tab:enum}\\")
    A(r"\toprule")
    A(r"\textbf{$S_1$} & \textbf{$(p,q,r)$} & \textbf{$R$} & \textbf{Status} \\")
    A(r"\midrule")
    A(r"\endfirsthead")
    A(r"\multicolumn{4}{c}{{\bfseries \tablename\ \thetable{} -- continued}} \\")
    A(r"\toprule")
    A(r"\textbf{$S_1$} & \textbf{$(p,q,r)$} & \textbf{$R$} & \textbf{Status} \\")
    A(r"\midrule")
    A(r"\endhead")
    A(r"\bottomrule")
    A(r"\endfoot")
    A(r"\bottomrule")
    A(r"\endlastfoot")

    last_S: int | None = None
    for S, orders, R, status in rows:
        if last_S is not None and S != last_S:
            A(r"\midrule")
        s_cell = f"{S}" if S != last_S else ""
        last_S = S

        triple = "(" + ",".join(str(m) for m in orders) + ")"
        if status == "collision":
            triple_cell = r"\textbf{$" + triple + r"$}"
            r_cell = r"\textbf{$" + f"{R.numerator}/{R.denominator}" + r"$}"
            status_cell = r"\textbf{collision}"
        else:
            triple_cell = f"${triple}$"
            r_cell = latex_fraction(R)
            status_cell = "unique"

        indent = "" if s_cell else "   "
        A(f"{s_cell:<3}{indent}& {triple_cell} & {r_cell} & {status_cell} \\\\".rstrip())

    A(r"\end{longtable}")
    return "\n".join(out) + "\n"


# --------------------------------------------------------------------------
# Table 1 -- tab:density, the cumulative counts
# --------------------------------------------------------------------------

def render_table1(records, field: str = "cum_pairs") -> str:
    """
    The manuscript's Table 1. `field` selects the counting convention;
    'cum_pairs' is the one the manuscript's printed values follow.
    """
    by_S = {r.S: r for r in records}
    out: list[str] = []
    A = out.append

    A("% Table 1 (tab:density) -- generated by code/make_table.py. Do not edit by hand.")
    A(f"% Counting convention: {field}. See review/convention-note.md.")
    A(r"\begin{table}[h!]")
    A(r"\centering")
    A(r"\caption{Exact cumulative count $\mathcal N(S)$ of two-coefficient "
      r"degeneracies, from enumeration through $S=600$.}")
    A(r"\label{tab:density}")
    A(r"\begin{tabular}{rrrr}")
    A(r"\toprule")
    A(r"$S$ & $\mathcal N(S)$ & $\mathcal N(S)/S$ & $\mathcal N(S)/S^2$ \\")
    A(r"\midrule")

    for S in CHECKPOINT_SUMS:
        if S not in by_S:
            raise RuntimeError(
                f"checkpoint S = {S} missing from the sweep; cannot emit Table 1"
            )
        n = getattr(by_S[S], field)
        ratio1 = Fraction(n, S)
        ratio2 = Fraction(n, S * S)
        A(f"{S:<4} & {n:<4} & {format_decimal(ratio1, 3)} & {format_decimal(ratio2, 4)} \\\\")

    A(r"\bottomrule")
    A(r"\end{tabular}")
    A(r"\end{table}")
    return "\n".join(out) + "\n"


def render_table1_both(records) -> str:
    """
    Supplementary variant showing both counting conventions side by side.
    Not a drop-in replacement for Table 1; it exists because the manuscript
    does not currently say which convention it uses.
    """
    by_S = {r.S: r for r in records}
    out: list[str] = []
    A = out.append

    A("% Supplementary variant of Table 1 showing both counting conventions.")
    A("% Generated by code/make_table.py. See review/convention-note.md.")
    A(r"\begin{table}[h!]")
    A(r"\centering")
    A(r"\caption{Exact cumulative count of two-coefficient degeneracies under both "
      r"counting conventions: $\mathcal N_{\mathrm{pairs}}(S)$ counts colliding pairs, "
      r"$\mathcal N_{\mathrm{classes}}(S)$ counts signature classes of size $>1$.}")
    A(r"\label{tab:density-both}")
    A(r"\begin{tabular}{rrrrr}")
    A(r"\toprule")
    A(r"$S$ & $\mathcal N_{\mathrm{pairs}}(S)$ & $\mathcal N_{\mathrm{classes}}(S)$ "
      r"& $\mathcal N_{\mathrm{pairs}}(S)/S^2$ & $\mathcal N_{\mathrm{classes}}(S)/S^2$ \\")
    A(r"\midrule")
    for S in CHECKPOINT_SUMS:
        rec = by_S[S]
        A(f"{S:<4} & {rec.cum_pairs:<5} & {rec.cum_classes:<5} & "
          f"{format_decimal(Fraction(rec.cum_pairs, S * S), 4)} & "
          f"{format_decimal(Fraction(rec.cum_classes, S * S), 4)} \\\\")
    A(r"\bottomrule")
    A(r"\end{tabular}")
    A(r"\end{table}")
    return "\n".join(out) + "\n"


# --------------------------------------------------------------------------

def main() -> int:
    TABLES_DIR.mkdir(parents=True, exist_ok=True)
    print(f"generating LaTeX tables into {TABLES_DIR.relative_to(REPO)}\n")

    # ---- Table 2 --------------------------------------------------------
    rows = collect_enum_rows()
    collisions = [(S, o) for S, o, _, st in rows if st == "collision"]
    print(f"  table2 (tab:enum): {len(rows)} triads over "
          f"{ENUM_LO} <= S_1 <= {ENUM_HI}")
    print(f"  collisions detected: {len(collisions)} row(s) -> "
          f"{[f'O{o}' for _, o in collisions]}")

    if len(collisions) != 2:
        raise RuntimeError(
            f"expected exactly two collision rows in {ENUM_LO}..{ENUM_HI}, "
            f"detected {len(collisions)}: {collisions}"
        )
    if {o for _, o in collisions} != {(2, 8, 8), (3, 3, 12)}:
        raise RuntimeError(
            f"detected collision rows {collisions} are not the expected "
            "O(2,8,8) / O(3,3,12) pair"
        )
    if {S for S, _ in collisions} != {18}:
        raise RuntimeError(f"collisions detected outside S_1 = 18: {collisions}")

    (TABLES_DIR / "table2.tex").write_text(render_table2(rows))
    print(f"  wrote {(TABLES_DIR / 'table2.tex').relative_to(REPO)}")

    # ---- Table 1 --------------------------------------------------------
    print(f"\n  sweeping to S = {max(CHECKPOINTS)} for the cumulative counts "
          "(this is the slow step)")
    records, _ = sweep(S_MIN, max(CHECKPOINTS))

    (TABLES_DIR / "table1.tex").write_text(render_table1(records, "cum_pairs"))
    print(f"  wrote {(TABLES_DIR / 'table1.tex').relative_to(REPO)}")

    (TABLES_DIR / "table1-both-conventions.tex").write_text(render_table1_both(records))
    print(f"  wrote {(TABLES_DIR / 'table1-both-conventions.tex').relative_to(REPO)}")

    print("\nPASS -- tables generated")
    return 0


if __name__ == "__main__":
    sys.exit(main())
