#!/usr/bin/env python3
"""Build paper/eigen/references.bib from fetched bibliographic records only.

The record handling (DOI content negotiation, arXiv and zbMATH Open records, the style tables, the
corrections each justified by a fetched record) is that of paper/jga/tools/build_bib.py, imported
unchanged; this script only replaces its table of sources by the works the eigen manuscript cites
and writes into paper/eigen/ (raw records in the git-ignored paper/eigen/fetched/bib/).

    python3 paper/eigen/tools/build_bib.py --fetch   # download the raw records
    python3 paper/eigen/tools/build_bib.py           # assemble references.bib from them

New records for this manuscript (round 3, items I2 and I5), each confirmed against Crossref and
zbMATH Open by the reference check of 2026-10-07:
  jorgensen1976  doi:10.2307/2373814 (zbMATH 0336.30007); the text is behind a bot wall (JSTOR):
                 an instrument gap, recorded in paper/eigen/SOURCES.md; the paper proves the special
                 case it needs and cites the original for the argument
  beardon1983    doi:10.1007/978-1-4612-1146-4 (GTM 91)
  mumford1971    doi:10.1090/s0002-9939-1971-0276410-4; Corollary 3 read from the fetched scan
  bers1972       doi:10.1007/bf02764631; abstract (fetched): the compactness theorem "remains valid
                 for groups containing elliptic and parabolic elements"
"""
import importlib.util
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent          # paper/eigen
JGA = HERE.parent / "jga" / "tools" / "build_bib.py"
spec = importlib.util.spec_from_file_location("jga_build_bib", JGA)
bb = importlib.util.module_from_spec(spec)
spec.loader.exec_module(bb)

KEEP = ["dggw2008", "donnelly1976", "ucar2017", "schueth2019", "drydenstrohmaier2009", "thurston1980",
        "hejhal1976", "iwaniec2002", "garbinjorgenson2020", "stanhope2005", "changdeturck1989",
        "griesermaronna2013", "buser1992", "linowitzvoight2015", "strohmaieruski2013", "schoberl1997",
        "arpack1998", "ngsolve", "crameri2023", "crameri2020"]
SOURCES = {k: bb.SOURCES[k] for k in KEEP}
SOURCES.update({
    "jorgensen1976": ("doi", "10.2307/2373814"),
    "beardon1983": ("doi", "10.1007/978-1-4612-1146-4"),
    "mumford1971": ("doi", "10.1090/s0002-9939-1971-0276410-4"),
    "bers1972": ("doi", "10.1007/bf02764631"),
})
bb.SOURCES = SOURCES
bb.HERE = HERE
bb.RAW = HERE / "fetched" / "bib"
bb.OUT = HERE / "references.bib"
# Crossref prints Jorgensen's name and title without diacritics; zbMATH 0336.30007 has them
bb.TITLE_SC["jorgensen1976"] = "On discrete groups of {M}{\\\"o}bius transformations"
bb.TITLE_SC["bers1972"] = "A remark on {M}umford's compactness theorem"
bb.TITLE_SC["mumford1971"] = "A remark on {M}ahler's compactness theorem"
bb.TITLE_SC["beardon1983"] = "The geometry of discrete groups"

if __name__ == "__main__":
    (HERE / "fetched").mkdir(exist_ok=True)
    zb = bb.RAW / "jorgensen1976_zb.json"
    if "--fetch" in sys.argv:
        bb.fetch_all()
        zb.write_bytes(bb.get("https://api.zbmath.org/v1/document/_search?search_string=an%3A0336.30007"
                              "&page=0&results_per_page=1"))
    bb.build()
    txt = bb.OUT.read_text(encoding="utf-8").replace("generated by paper/jga/tools/build_bib.py",
                                                       "generated by paper/eigen/tools/build_bib.py")
    # the letter o-slash of zbMATH 0336.30007, which the Crossref record writes as "o"
    txt = txt.replace("author      = {Jorgensen, T.}", "author      = {J{\\o}rgensen, T.}")
    txt = txt.replace("author      = {Jorgensen, Troels}", "author      = {J{\\o}rgensen, Troels}")
    # the page range of zbMATH 0336.30007 (Crossref gives only the first page)
    assert '"739-749"' in zb.read_text(encoding="utf-8")
    txt = txt.replace("  pages       = {739},", "  pages       = {739--749},")
    bb.OUT.write_text(txt, encoding="utf-8")
