#!/usr/bin/env python3
"""Summarise the last latexmk build of paper/jga/manuscript.tex into paper/jga/BUILD.md.

    cd paper/jga && latexmk manuscript.tex && python3 tools/build_report.py
"""
import re
import subprocess
from collections import Counter
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
LOG = HERE / "build" / "manuscript.log"
BLG = HERE / "build" / "manuscript.blg"
PDF = HERE / "build" / "manuscript.pdf"


def main():
    log = LOG.read_text(errors="replace")
    blg = BLG.read_text(errors="replace")
    pages = re.search(r"Output written on \S+ \((\d+) pages", log).group(1)
    errors = re.findall(r"^! .*", log, re.M)
    undef_ref = re.findall(r"Reference `[^']+' on page \d+ undefined", log)
    undef_cit = re.findall(r"Citation `[^']+' on page \d+ undefined", log)
    overfull = [float(x) for x in re.findall(r"Overfull \\hbox \(([\d.]+)pt too wide\)", log)]
    over1 = [x for x in overfull if x > 1.0]
    warn = Counter(re.sub(r"\s+on input line.*|\s+\(.*", "", w).strip()
                   for w in re.findall(r"^((?:LaTeX|Package)[^\n]*Warning[^\n]*)", log, re.M))
    underfull = len(re.findall(r"^Underfull", log, re.M))
    bib_warn = re.findall(r"^Warning--.*", blg, re.M)
    info = subprocess.run(["pdfinfo", str(PDF)], capture_output=True, text=True).stdout
    lines = [
        "# BUILD: last build of the JGA manuscript",
        "",
        "Command: `cd paper/jga && latexmk manuscript.tex` (pdflatex and BibTeX; output in `paper/jga/build/`,",
        "which is git-ignored; the PDF is not committed). Generated by `tools/build_report.py`.",
        "",
        "| check | result |",
        "|---|---|",
        f"| pages | {pages} |",
        f"| LaTeX errors | {len(errors)} |",
        f"| undefined references | {len(undef_ref)} |",
        f"| undefined citations | {len(undef_cit)} |",
        f"| overfull boxes above 1pt | {len(over1)} (all overfull: {len(overfull)}) |",
        f"| BibTeX warnings | {len(bib_warn)} |",
        f"| underfull boxes (reported, not errors) | {underfull} |",
        "",
        "## Remaining warnings",
        "",
    ]
    if warn:
        lines += ["| count | warning |", "|---|---|"] + [f"| {c} | {w} |" for w, c in sorted(warn.items(), key=lambda x: -x[1])]
    else:
        lines.append("None.")
    lines += [
        "",
        "Notes on the remaining warnings:",
        "",
        "- `Difference ... between bookmark levels`: the class's `\\bmhead` paragraph headings in the back",
        "  matter sit directly under starred sections; this affects only the PDF bookmarks.",
        "- `Font shape U/rsfs/m/n ... not available` and `Size substitutions`: the class loads `mathrsfs`",
        "  at sizes for which the font has no exact design size; substitution is by the nearest size.",
        "- Underfull boxes are the class's ragged page bottoms (`\\raggedbottom`) and a few loose lines;",
        "  none is visible as a defect.",
        "",
        "## PDF metadata",
        "",
        "```",
        info.strip(),
        "```",
        "",
    ]
    (HERE / "BUILD.md").write_text("\n".join(lines))
    print("\n".join(lines[:14]))


if __name__ == "__main__":
    main()
