"""T1. The front end: first n heat coefficients <-> I_n = (R, P_1, ..., P_{2n-3}), n = 3..8.

H = L I + h0 with L lower triangular (exact rationals), so I = L^{-1} (H - h0).
Checks (asserts, exact):
  (a) smooth coefficients alpha_j: Ucar (4.35) == independent Selberg identity-term derivation;
  (b) cone polynomials p_l: stated forms in theory/cone-coefficients/ucar-source.md, and
      numerics/theory.py b_cone (independent implementation) for orders 2..40, l <= 6;
  (c) heat_direct(m) == L I_n(m) + h0 for the named multisets and random rational ones;
  (d) L L^{-1} = Id; the leading blocks of L do not depend on n;
  (e) the review claim (DEFECTS.md MAJ-05): amplification factors 12, 360, 2520.
Writes front_end_output.md (tables).  Exits nonzero on any failure.
"""
import os
import random
import sys
from fractions import Fraction as Fr

from stab_common import (alpha_smooth, alpha_smooth_selberg, cone_poly, front_end, heat_direct,
                         identity, invariants, mat_inv, mat_mul, mat_vec)

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "..", "numerics"))
import theory as numerics_theory  # noqa: E402  (read-only cross-check)

NAMED = [(2, 8, 8), (3, 3, 12), (3, 10, 15, 30), (4, 5, 21, 28), (2, 3, 7), (4, 4, 4), (7, 7, 7),
         (3, 3, 4, 4), (5, 5, 5, 5), (2, 2, 2, 3), (2, 2, 2, 2, 3), (3, 3, 3, 3, 3, 3)]


def fmt(x):
    return str(x) if x.denominator == 1 else f"{x.numerator}/{x.denominator}"


def main():
    out = []
    # (a) smooth coefficients, two derivations
    for j in range(0, 12):
        assert alpha_smooth(j) == alpha_smooth_selberg(j), j
    assert [alpha_smooth(j) for j in range(3)] == [1, Fr(-1, 3), Fr(1, 15)]
    # (b) cone polynomials
    stated = {0: [Fr(-1, 12), Fr(1, 12)],
              1: [Fr(-11, 360), Fr(1, 36), Fr(1, 360)],
              2: [Fr(-37, 5040), Fr(1, 180), Fr(1, 720), Fr(1, 2520)],
              3: [Fr(-19, 10080), Fr(1, 945), Fr(1, 2160), Fr(1, 3780), Fr(1, 10080)]}
    for l, want in stated.items():
        assert cone_poly(l) == [Fr(w) for w in want], l
    for l in range(7):
        p = cone_poly(l)
        assert sum(p) == 0, l                              # p_l(1) = 0
        assert p[-1] > 0 and len(p) == l + 2
        for k in range(2, 41):
            assert numerics_theory.b_cone(l, k) == Fr(-1) ** l * sum(c * Fr(k) ** (2 * i) for i, c in enumerate(p)) / k
    # (c), (d)
    random.seed(20261001)
    Lmax, _ = front_end(8)
    for n in range(3, 9):
        L, h0 = front_end(n)
        assert all(L[i][j] == Lmax[i][j] for i in range(n) for j in range(n)), n
        assert all(L[i][j] == 0 for i in range(n) for j in range(i + 1, n))
        Li = mat_inv(L)
        assert mat_mul(L, Li) == identity(n)
        tests = [m for m in NAMED if len(m) == n]
        tests += [[Fr(random.randint(2, 60), random.randint(1, 4)) for _ in range(n)] for _ in range(4)]
        for m in tests:
            H = heat_direct(m, n)
            I = invariants(m)
            assert H == [a + b for a, b in zip(mat_vec(L, I), h0)], (n, m)
            assert I == mat_vec(Li, [a - b for a, b in zip(H, h0)]), (n, m)
    # numerics/theory.py pillow coefficients agree for the two pillows
    for pqr in [(2, 8, 8), (3, 3, 12)]:
        pc = numerics_theory.pillow_coeffs(pqr, 6)
        H = heat_direct(pqr, 8)
        for nu in range(-1, 7):
            assert pc["coef"][nu] == H[nu + 1], (pqr, nu)

    # ---------------------------------------------------------------- tables
    L, h0 = front_end(8)
    Li = mat_inv(L)
    names = ["R", "P1", "P3", "P5", "P7", "P9", "P11", "P13"]
    hn = [f"H{nu}" for nu in range(-1, 7)]
    out.append("# T1 front end: exact tables (generated by front_end.py)\n")
    out.append("H_nu is the coefficient of t^nu in Z(t), nu = -1..6; H_{-1} = Area/(4 pi).\n")
    out.append("## L (H = L I + h0), rows H_{-1}..H_6, columns R, P_1, ..., P_13\n")
    out.append("| | " + " | ".join(names) + " |")
    out.append("|---" * 9 + "|")
    for i in range(8):
        out.append(f"| {hn[i]} | " + " | ".join(fmt(L[i][j]) if j <= i else "" for j in range(8)) + " |")
    out.append("\nh0(n) = (n-2)/2 * (1, alpha_1, ..., alpha_7), alpha = "
               + ", ".join(fmt(alpha_smooth(j)) for j in range(1, 8)) + "\n")
    out.append("## L^{-1} (I = L^{-1}(H - h0))\n")
    out.append("| | " + " | ".join(hn) + " |")
    out.append("|---" * 9 + "|")
    for i in range(8):
        out.append(f"| {names[i]} | " + " | ".join(fmt(Li[i][j]) if j <= i else "" for j in range(8)) + " |")
    out.append("\n## Amplification\n")
    out.append("diag = |(L^{-1})_{rr}| = 1/|L_rr|; row-sum = sum_c |(L^{-1})_{rc}| (worst case for |dH_nu| <= delta, all nu);\n"
               "the row-sum for I_r uses only the first r+1 coefficients, so it is the same for every n >= r+1.\n")
    out.append("| invariant | diag factor | row-sum factor | row-sum / diag |")
    out.append("|---|---|---|---|")
    diag = [abs(Li[r][r]) for r in range(8)]
    rows = [sum(abs(x) for x in Li[r]) for r in range(8)]
    for r in range(8):
        out.append(f"| {names[r]} | {fmt(diag[r])} | {fmt(rows[r])} = {float(rows[r]):.6g} | {float(rows[r] / diag[r]):.4f} |")
    # (e) the review claim
    assert diag[1] == 12 and diag[2] == 360 and diag[3] == 2520
    assert rows[1] > 12 and rows[2] > 360 and rows[3] > 2520
    out.append("\n## Relative amplification at the named multisets\n")
    out.append("kappa_r = sum_c |(L^{-1})_{rc}| |H_c| / |I_r|: relative error of I_r per unit relative error in every H_c.\n")
    out.append("| m | " + " | ".join(names[:6]) + " |")
    out.append("|---" * 7 + "|")
    for m in NAMED:
        n = len(m)
        Ln, h0n = front_end(n)
        Lin = mat_inv(Ln)
        H = heat_direct(m, n)
        I = invariants(m)
        kap = [sum(abs(Lin[r][c]) * abs(H[c]) for c in range(n)) / abs(I[r]) for r in range(n)]
        out.append(f"| {m} | " + " | ".join(f"{float(k):.4g}" for k in kap) + " |" + " |" * (6 - n))
    text = "\n".join(out) + "\n"
    with open(os.path.join(HERE, "front_end_output.md"), "w") as f:
        f.write(text)
    print(text)
    print("front_end.py: all asserts passed")


if __name__ == "__main__":
    main()
