"""T2. I_n -> e: the Theorem B linear system, its inverse, and explicit Lipschitz constants.

Proved in proof.md section 3; checked here, exactly:
  (a) Hurwitz factorisation  B = S M,  where B[k][j] = (-1)^{j+1} e_{2k+1-j} and
      S[k][i] = e_{2(k-i)} (k <= n-2), S[n-1][n-1] = (-1)^n e_n;
      det B = (-1)^{n(n-1)/2} prod_{i<j}(m_i+m_j),
      det M = (-1)^{n(n+1)/2} prod_{i<j}(m_i+m_j)/e_n   (c_n for every n, Lemma S2.1);
  (b) the derivative of the inverse map:  D_I e = -M^{-1} N,  N = d(M e - b)/dI at fixed e,
      det N = -e_n / prod_{j<n-1} (2j+1); checked against an exact finite difference;
  (c) the normalised bounds of Theorem S2 hold at every test multiset:
        ||M^-1||_inf (normalised) <= n * Lambda * ||S||_inf / prod(m_i+m_j)   (Lambda: column norms of B)
                                <= n * binom(2n,n)^{n/2} * 2^{n-1} / prod(m_i+m_j)
      and the perturbation bound  ||de||  <= ||M^-1|| ||r|| / (1 - beta)  for random data
      perturbations of normalised size eta (exact rational perturbations, exact solve);
  (d) the majorant constants sigma_k(n) = [w^k] artanh(w) sec^2((n+1) artanh w) and
      |dT_k| <= eta sigma_k(n) for normalised data errors eta <= 1.
Writes lipschitz_e_output.md.  Exits nonzero on any failure.
"""
import os
import random
from fractions import Fraction as Fr
from math import comb

from stab_common import (U_series, c_sign, det, elementary, hurwitz_B, hurwitz_S, inf_norm, invariants,
                         mat_inv, mat_mul, mat_vec, pair_product, ser_mul, ser_tan, ser_tanh, theorem_B_system)

HERE = os.path.dirname(os.path.abspath(__file__))
NAMED = [(2, 8, 8), (3, 3, 12), (3, 10, 15, 30), (4, 5, 21, 28), (2, 3, 7), (4, 4, 4), (7, 7, 7),
         (3, 3, 4, 4), (5, 5, 5, 5), (2, 2, 2, 3), (2, 2, 2, 2, 3), (2, 2, 100)]


def normalise(m):
    mu = max(Fr(x) for x in m)
    return [Fr(x) / mu for x in m], mu


def N_matrix(I, e):
    """N = d(M e - b)/dI at fixed e (exact, by the chain rule through T = tanh U)."""
    n = len(I)
    Nn = 2 * n - 3
    Podd = {2 * k - 1: I[k] for k in range(1, n)}
    U = U_series(Podd, Nn)
    T = ser_tanh(U, Nn)
    sech2 = [Fr(int(i == 0)) - x for i, x in enumerate(ser_mul(T, T, Nn))]
    Nm = [[Fr(0)] * n for _ in range(n)]
    # dT_k/dP_l = [z^k] sech^2(U) z^l / l
    for j in range(n - 1):
        for i in range(j + 1):
            idx = 2 * j - 2 * i
            if idx > n:
                continue
            ek = e[idx]
            for l in range(1, n):
                P = 2 * l - 1
                if P <= 2 * i + 1:
                    Nm[j][l] -= ek * sech2[2 * i + 1 - P] / P
    Nm[n - 1][0] = -e[n]
    return Nm


def column_norm_bound(B):
    """Lambda = prod_c ||col_c||_2 (all column norms are >= 1 in normalised units),
    returned as an upper bound via exact squares: Lambda^2 = prod ||col_c||^2."""
    n = len(B)
    sq = [sum(B[k][c] ** 2 for k in range(n)) for c in range(n)]
    return sq


def sigma(n, kmax):
    """sigma_k(n) = [w^k] artanh(w) * sec^2((n+1) artanh(w))."""
    A = [Fr(0)] * (kmax + 1)
    for k in range(1, kmax + 1, 2):
        A[k] = Fr(1, k)
    T = ser_tan([(n + 1) * a for a in A], kmax)
    sec2 = [Fr(int(i == 0)) + x for i, x in enumerate(ser_mul(T, T, kmax))]
    return ser_mul(A, sec2, kmax)


def theta(n, eta, kmax):
    """[w^k] (tan((n+eta) artanh w) - tan(n artanh w))."""
    A = [Fr(0)] * (kmax + 1)
    for k in range(1, kmax + 1, 2):
        A[k] = Fr(1, k)
    t1 = ser_tan([(n + eta) * a for a in A], kmax)
    t0 = ser_tan([n * a for a in A], kmax)
    return [x - y for x, y in zip(t1, t0)]


def isqrt_up(x):
    """an upper bound for sqrt(x), x a nonnegative Fraction (float with margin, then verified)."""
    import math
    s = Fr(math.sqrt(float(x)) * (1 + 1e-12) + 1e-300)
    assert s * s >= x
    return s


def main():
    out = ["# T2: I_n -> e (generated by lipschitz_e.py)\n"]
    random.seed(7)
    # (a) factorisation and determinants, n = 2..10
    for n in range(2, 11):
        for _ in range(4):
            m = [Fr(random.randint(1, 50), random.randint(1, 6)) for _ in range(n)]
            e = elementary(m)
            M, b, _ = theorem_B_system(invariants(m))
            assert mat_vec(M, e[1:]) == b
            B, S = hurwitz_B(e, n), hurwitz_S(e, n)
            assert mat_mul(S, M) == B, n
            P = pair_product(m)
            assert det(B) == (-1) ** (n * (n - 1) // 2) * P, n
            assert det(M) == c_sign(n) * P / e[n], n
            assert det(S) == (-1) ** n * e[n]
    out.append("(a) B = S M, det B = (-1)^{n(n-1)/2} prod(m_i+m_j), det M = (-1)^{n(n+1)/2} prod(m_i+m_j)/e_n: "
               "checked exactly at 4 random rational multisets for each n = 2..10.\n")
    # (b) D_I e = -M^{-1} N, and det N
    for n in range(2, 8):
        for _ in range(3):
            m = [Fr(random.randint(2, 30)) for _ in range(n)]
            e = elementary(m)
            I = invariants(m)
            M, b, _ = theorem_B_system(I)
            Nm = N_matrix(I, e)
            dprod = 1
            for j in range(n - 1):
                dprod *= 2 * j + 1
            assert det(Nm) == -e[n] / dprod, n
            J = [[-x for x in row] for row in mat_mul(mat_inv(M), Nm)]   # D_I e
            # exact finite difference: e(I + h u) - e(I) = h J u + O(h^2)
            h = Fr(1, 10 ** 12)
            for c in range(n):
                I2 = list(I)
                I2[c] += h
                M2, b2, _ = theorem_B_system(I2)
                e2 = mat_vec(mat_inv(M2), b2)
                for k in range(n):
                    fd = (e2[k] - e[k + 1]) / h
                    scale = max(abs(J[k][c]), Fr(1))
                    assert abs(fd - J[k][c]) <= Fr(1, 10 ** 6) * scale * (1 + sum(abs(x) for x in e)), (n, k, c)
    out.append("(b) D_I e = -M^{-1} N with det N = -e_n/prod_{j=0}^{n-2}(2j+1): checked n = 2..7 "
               "(determinant exact; derivative against an exact finite difference, h = 1e-12).\n")
    # (c) bounds at the named multisets
    out.append("## Normalised conditioning at test multisets (mu = max m_i)\n")
    out.append("| m | prod(m^_i+m^_j) | ||M^-1||_inf exact | Hadamard bound n*Lambda*||S||/prod | closed form | ||D_I e|| (normalised) |")
    out.append("|---|---|---|---|---|---|")
    for m in NAMED:
        n = len(m)
        mh, mu = normalise(m)
        e = elementary(mh)
        I = invariants(mh)
        M, b, _ = theorem_B_system(I)
        Mi = mat_inv(M)
        nm = inf_norm(Mi)
        B, S = hurwitz_B(e, n), hurwitz_S(e, n)
        sq = column_norm_bound(B)
        assert all(s >= 1 for s in sq)
        lam2 = 1
        for s in sq:
            lam2 *= s
        lam = isqrt_up(lam2)
        P = pair_product(mh)
        had = n * lam * inf_norm(S) / P
        closed = n * isqrt_up(Fr(comb(2 * n, n)) ** n) * 2 ** (n - 1) / P
        assert nm <= had <= closed, m
        J = [[-x for x in row] for row in mat_mul(Mi, N_matrix(I, e))]
        out.append(f"| {m} | {float(P):.4g} | {float(nm):.4g} | {float(had):.4g} | {float(closed):.4g} | {float(inf_norm(J)):.4g} |")
    # (d) majorant constants and the perturbation lemma, random perturbations
    out.append("\n## Majorant constants sigma_k(n) (odd k <= 2n-3)\n")
    out.append("| n | sigma_1, sigma_3, ... |")
    out.append("|---|---|")
    for n in range(3, 9):
        kmax = 2 * n - 3
        s = sigma(n, kmax)
        for eta in (Fr(1), Fr(1, 2), Fr(1, 10), Fr(1, 1000)):
            th = theta(n, eta, kmax)
            for k in range(1, kmax + 1, 2):
                assert 0 <= th[k] <= eta * s[k], (n, k, eta)
        out.append(f"| {n} | " + ", ".join(f"{float(s[k]):.4g}" for k in range(1, kmax + 1, 2)) + " |")
    # random exact perturbations: |de| <= ||M^-1|| ||r|| / (1 - beta) and |dT_k| <= eta sigma_k
    worst = 0.0
    for m in NAMED:
        n = len(m)
        mh, mu = normalise(m)
        e = elementary(mh)
        I = invariants(mh)
        M, b, T = theorem_B_system(I)
        Mi = mat_inv(M)
        s = sigma(n, 2 * n - 3)
        for _ in range(20):
            eta = Fr(1, 10 ** random.randint(2, 8))
            dI = [eta * Fr(random.randint(-1000, 1000), 1000) for _ in range(n)]
            I2 = [x + d for x, d in zip(I, dI)]
            M2, b2, T2 = theorem_B_system(I2)
            for k in range(1, 2 * n - 2, 2):
                assert abs(T2[k] - T[k]) <= eta * s[k], (m, k)
            dM = [[x - y for x, y in zip(r2, r1)] for r2, r1 in zip(M2, M)]
            r = [x - y for x, y in zip(b2, mat_vec(M2, e[1:]))]
            beta = inf_norm(Mi) * inf_norm(dM)
            if beta >= 1:
                continue
            e2 = mat_vec(mat_inv(M2), b2)
            de = max(abs(x - y) for x, y in zip(e2, e[1:]))
            bound = inf_norm(Mi) * max(abs(x) for x in r) / (1 - beta)
            assert de <= bound, m
            worst = max(worst, float(de / bound))
    out.append(f"\n(c,d) Perturbation lemma and |dT_k| <= eta sigma_k(n): 20 random exact perturbations per test multiset, "
               f"normalised sizes 1e-2..1e-8; all bounds hold; largest ratio actual/bound = {worst:.3f}.\n")
    text = "\n".join(out) + "\n"
    with open(os.path.join(HERE, "lipschitz_e_output.md"), "w") as f:
        f.write(text)
    print(text)
    print("lipschitz_e.py: all asserts passed")


if __name__ == "__main__":
    main()
