"""T3. e -> orders: the cluster lemma (Rouche) and the sharpness of the exponent 1/k.

Lemma S3 (proof.md section 4), normalised units (mu = max m_i, hats dropped):
  q(z) = prod (z - m_i) = sum_j (-1)^j e_j z^{n-j};  q~ the same with e~, |e~_j - e_j| <= eps.
  For a distinct order a of multiplicity k, gap g_a = min_{b != a} |a - b| (inf if none),
  Q_a = prod_{b != a} |a - b|^{k_b}:  if  r_a := (2^{1-k} 3^n eps / Q_a)^{1/k} <= min(g_a, 1)/2,
  then q~ has exactly k roots in |z - a| < r_a.
Checks:
  (a) the lemma against high-precision root finding, random real perturbations of e;
  (b) sharpness, k = 2, realisable: m(s) = (a+s, a-s, c...): the exact heat-data change is
      s^2 C + O(s^4) while the orders move by s;  ratio s / ||dH||^{1/2} converges;
  (c) sharpness, k = 3 and k = 4, general data: m(s) = (a + s w^j) (w a k-th root of unity) has
      REAL heat data, ||dH|| = O(s^k), orders move by s;
  (d) the realisable exponent for a triple cluster: for REAL perturbations of (a,a,a),
      max|d|^2 <= C ||dI||  (exponent 1/2, not 1/3), with the explicit C = 1/(2a) * |(-3a^2, 1)| row,
      checked on random real perturbations.
Writes roots_holder_output.md.  Exits nonzero on any failure.
"""
import os
import random
from fractions import Fraction as Fr

import mpmath as mp

from stab_common import elementary, front_end, heat_direct, invariants, mat_vec

HERE = os.path.dirname(os.path.abspath(__file__))
mp.mp.dps = 60


def clusters(m):
    out = {}
    for x in m:
        out[Fr(x)] = out.get(Fr(x), 0) + 1
    return out


def r_bound(m, eps):
    """normalised radii r_a of Lemma S3 (as floats with mp precision); None if not applicable."""
    n = len(m)
    cl = clusters(m)
    res = {}
    for a, k in cl.items():
        others = [b for b in cl if b != a]
        g = min((abs(a - b) for b in others), default=None)
        Q = Fr(1)
        for b in others:
            Q *= abs(a - b) ** cl[b]
        r = (mp.mpf(2) ** (1 - k) * mp.mpf(3) ** n * mp.mpf(eps.numerator) / eps.denominator / mp.mpf(Q.numerator) * Q.denominator) ** (mp.mpf(1) / k)
        lim = min(g if g is not None else Fr(1), Fr(1)) / 2
        res[a] = (k, r, r <= mp.mpf(lim.numerator) / lim.denominator)
    return res


def roots_from_e(e):
    n = len(e) - 1
    coeffs = [mp.mpf((-1) ** j * e[j].numerator) / e[j].denominator for j in range(n + 1)]
    return mp.polyroots(coeffs, maxsteps=500, extraprec=400)


def I_from_e(e, n):
    """(R, P_1, P_3, ..., P_{2n-3}) from e_0..e_n by Newton's identities (exact)."""
    N = 2 * n - 3
    E = lambda i: e[i] if 0 <= i <= n else Fr(0)
    p = [Fr(0)] * (N + 1)
    for k in range(1, N + 1):
        s = (-1) ** (k - 1) * k * E(k)
        for i in range(1, k):
            s += (-1) ** (k - 1 + i) * E(k - i) * p[i]
        p[k] = s
    return [e[n - 1] / e[n]] + [p[2 * l - 1] for l in range(1, n)]


def H_from_e(e, n):
    L, h0 = front_end(n)
    return [a + b for a, b in zip(mat_vec(L, I_from_e(e, n)), h0)]


def poly_mul(a, b):
    out = [Fr(0)] * (len(a) + len(b) - 1)
    for i, x in enumerate(a):
        for j, y in enumerate(b):
            out[i + j] += x * y
    return out


def main():
    out = ["# T3: roots (generated by roots_holder.py)\n"]
    random.seed(11)
    # sanity: H_from_e agrees with the direct evaluation
    for m in [(2, 8, 8), (3, 3, 12), (3, 10, 15, 30), (2, 2, 2, 3)]:
        assert H_from_e(elementary(m), len(m)) == heat_direct(m, len(m))
    # (a) Lemma S3 against root finding (normalised multisets)
    tests = [(2, 8, 8), (3, 3, 12), (3, 10, 15, 30), (4, 5, 21, 28), (4, 4, 4), (3, 3, 4, 4), (2, 2, 2, 3),
             (5, 5, 5, 5), (2, 3, 7)]
    worst = {1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0}
    ntest = 0
    for m in tests:
        mu = max(m)
        mh = [Fr(x, mu) for x in m]
        e = elementary(mh)
        for _ in range(40):
            eps = Fr(1, 10 ** random.randint(3, 12))
            de = [Fr(0)] + [eps * Fr(random.randint(-10 ** 6, 10 ** 6), 10 ** 6) for _ in range(len(m))]
            rts = roots_from_e([x + d for x, d in zip(e, de)])
            for a, (k, r, ok) in r_bound(mh, eps).items():
                if not ok:
                    continue
                am = mp.mpf(a.numerator) / a.denominator
                inside = [z for z in rts if abs(z - am) < r]
                assert len(inside) == k, (m, a, eps, k, len(inside))
                worst[k] = max(worst[k], float(max(abs(z - am) for z in inside) / r))
                ntest += 1
    out.append(f"(a) Lemma S3 checked in {ntest} cluster instances (9 multisets, random e-perturbations of normalised size "
               f"1e-3..1e-12): every cluster has exactly k roots inside r_a. Largest (actual displacement)/r_a by k: "
               + ", ".join(f"k={k}: {v:.3g}" for k, v in worst.items() if v) + ".\n")
    # (b) k = 2 realisable sharpness
    out.append("## (b) Exponent 1/2 is sharp at a double order (realisable perturbation)\n")
    out.append("m(s) = (a+s, a-s, c, ...): orders move by s, heat data move by O(s^2).\n")
    out.append("| base | s | max|dH_nu| | s/sqrt(max|dH|) |")
    out.append("|---|---|---|---|")
    for base, a, rest in [((2, 8, 8), 8, [2]), ((3, 3, 12), 3, [12]), ((3, 3, 4, 4), 3, [4, 4])]:
        n = len(base)
        H0 = heat_direct(base, n)
        ratios = []
        for p in range(2, 7):
            s = Fr(1, 10 ** p)
            ms = [a + s, a - s] + rest
            dH = max(abs(x - y) for x, y in zip(heat_direct(ms, n), H0))
            ratio = mp.mpf(s.numerator) / s.denominator / mp.sqrt(mp.mpf(dH.numerator) / dH.denominator)
            ratios.append(ratio)
            out.append(f"| {base} | 1e-{p} | {float(dH):.4g} | {float(ratio):.6g} |")
        assert abs(ratios[-1] - ratios[-2]) < 1e-6 * ratios[-1]          # converges: dH ~ s^2
        assert ratios[-1] > 0.01
    # exact s^2 coefficient for (8+s, 8-s, 2)
    out.append("\nExact, a = 8, c = 2: dR = 2 s^2/(8(64 - s^2)), dP_1 = 0, dP_3 = 48 s^2 (asserted).\n")
    for s in [Fr(1, 3), Fr(1, 7), Fr(2, 5)]:
        dI = [x - y for x, y in zip(invariants([8 + s, 8 - s, 2]), invariants([8, 8, 2]))]
        assert dI == [2 * s ** 2 / (8 * (64 - s ** 2)), 0, 48 * s ** 2]
    # (c) k-fold, general (complex-order) data: (z - a)^k - s^k
    out.append("## (c) Exponent 1/k is sharp for general data (k = 3, 4)\n")
    out.append("q_s(z) = ((z-a)^k - s^k) * g(z): real coefficients, real heat data, roots a + s w^j.\n")
    out.append("| base | k | s | max|dH_nu| | s/max|dH|^{1/k} |")
    out.append("|---|---|---|---|---|")
    from math import comb
    for a, k, rest in [(4, 3, []), (7, 3, []), (5, 4, []), (2, 3, [3])]:
        n = k + len(rest)
        base = [a] * k + rest
        e0 = elementary(base)
        H0 = H_from_e(e0, n)
        g = [Fr(1)]
        for x in rest:
            g = poly_mul(g, [Fr(1), Fr(-x)])           # monic, descending powers
        ratios = []
        for p in range(1, 6):
            s = Fr(1, 10 ** p)
            cl = [Fr(comb(k, j)) * Fr(-a) ** j for j in range(k + 1)]   # (z - a)^k, descending
            cl[k] -= s ** k
            q = poly_mul(cl, g)
            e = [(-1) ** j * q[j] for j in range(n + 1)]
            H = H_from_e(e, n)
            assert all(isinstance(x, Fr) for x in H)
            dH = max(abs(x - y) for x, y in zip(H, H0))
            rts = roots_from_e(e)
            disp = max(min(abs(z - x) for x in base) for z in rts)
            assert abs(disp - mp.mpf(s.numerator) / s.denominator) < mp.mpf(10) ** -40
            ratio = mp.mpf(s.numerator) / s.denominator / (mp.mpf(dH.numerator) / dH.denominator) ** (mp.mpf(1) / k)
            ratios.append(ratio)
            out.append(f"| {tuple(base)} | {k} | 1e-{p} | {float(dH):.4g} | {float(ratio):.6g} |")
        assert abs(ratios[-1] - ratios[-2]) < 1e-3 * ratios[-1]
    # (d) realisable triple cluster: exponent 1/2
    out.append("\n## (d) Realisable perturbations of a triple order: exponent 1/2\n")
    out.append("For real d with |d_i| <= a:  (P_3 - 3a^2 P_1)(a+d) - (same)(a) = 3a sum d_i^2 + sum d_i^3 >= 2a sum d_i^2,\n"
               "so max|d_i|^2 <= sum d^2 <= |dP_3 - 3a^2 dP_1|/(2a): Hoelder 1/2 for heat data of real multisets.\n")
    worst_d = 0.0
    for a in (4, 7, 10):
        for _ in range(300):
            sc = Fr(1, 10 ** random.randint(1, 6))
            d = [sc * Fr(random.randint(-1000, 1000), 1000) for _ in range(3)]
            I1 = invariants([a + x for x in d])
            I0 = invariants([a, a, a])
            lhs = max(abs(x) for x in d) ** 2
            rhs = abs((I1[2] - I0[2]) - 3 * a * a * (I1[1] - I0[1])) / (2 * a)
            assert lhs <= rhs + Fr(0), (a, d)
            if rhs:
                worst_d = max(worst_d, float(lhs / rhs))
    out.append(f"Checked on 900 random real perturbations (a = 4, 7, 10); largest max|d|^2 / bound = {worst_d:.3f}.\n")
    text = "\n".join(out) + "\n"
    with open(os.path.join(HERE, "roots_holder_output.md"), "w") as f:
        f.write(text)
    print(text)
    print("roots_holder.py: all asserts passed")


if __name__ == "__main__":
    main()
