"""F2 (Section 2): the (2,8,8) and (3,3,12) triangle-group tilings on the hyperboloid.

Exact geometry, no stylisation. The upper sheet x0 = sqrt(1 + x1^2 + x2^2) of the hyperboloid
model, with the Minkowski form <x, y> = -x0 y0 + x1 y1 + x2 y2. The triangle T_{p,q,r} is
numerics/geometry.Triangle (vertex A, angle pi/p, at the origin of the disk; B, angle pi/q, on
the positive real axis), mapped to the hyperboloid by z -> ((1+|z|^2), 2 Re z, 2 Im z)/(1-|z|^2).
The tiling is generated by the reflections in the sides of T (reflection in the plane through 0
containing two vertices), breadth first, every tile whose three vertices lie within hyperbolic
distance D_MAX of A; the drawing is clipped to the cap x0 <= cosh(D_RIM) (distance D_RIM from A),
whose rim is drawn. The view is steeper than the sheet, so the projection is one-to-one and the
2D clip is the clip on the surface. Sides are drawn as geodesics: the hyperboloid points of the plane through
0 and their two endpoints. Orthographic view; tiles drawn back to front.

Fills: T (dark tone of the pillow's hue) and its mirror image in the side AB (light tone), which
together form a fundamental domain of the orientation-preserving subgroup, i.e. one copy of the
pillow; the other tiles alternate white and faint grey by orientation.

Asserted: Triangle.verify() (angles, area, side lengths, mpmath); every vertex lies on the
hyperboloid; the whole pillow (T and its mirror image) lies inside the cap; the drawn cap is covered by the tiles (4000 random points); the product of the reflections in the two sides through a vertex of angle pi/k has
order exactly k; every reflection preserves the form; the tiles are distinct and each has area
pi(1 - 1/p - 1/q - 1/r) by Gauss-Bonnet (angles of every tile recomputed).
"""
import numpy as np

from common_import import import_from
from figlib import check_only, finish, fs

D_RIM = 2.4                  # the drawn cap: x0 <= cosh(D_RIM)
D_MAX = D_RIM + 2.4          # tiles generated: all vertices within D_MAX (they cover the cap)
J = np.diag([-1.0, 1.0, 1.0])
VIEW = {"elev_deg": 58.0, "azim_deg": -62.0}


def mink(a, b):
    return -a[0] * b[0] + a[1] * b[1] + a[2] * b[2]


def to_hyperboloid(z):
    r2 = abs(z) ** 2
    return np.array([(1 + r2), 2 * z.real, 2 * z.imag]) / (1 - r2)


def reflection(u, v):
    n = J @ np.cross(u, v)                       # <n, u> = <n, v> = 0
    nn = mink(n, n)
    assert nn > 0                                # spacelike normal: a geodesic plane
    return np.eye(3) - 2 * np.outer(n, J @ n) / nn


def angle_at(P, Q, R):
    """Hyperbolic angle at P of the geodesics to Q and R (tangent vectors in the Minkowski form)."""
    tq = Q + mink(P, Q) * P
    tr = R + mink(P, R) * P
    return np.arccos(np.clip(mink(tq, tr) / np.sqrt(mink(tq, tq) * mink(tr, tr)), -1, 1))


def tiling(pqr):
    geo, _ = import_from("numerics", "geometry")
    T = geo.Triangle(*pqr)
    T.verify()
    V = [to_hyperboloid(complex(complex(z).real, complex(z).imag)) for z in (T.A, T.B, T.C)]
    for v in V:
        assert abs(mink(v, v) + 1) < 1e-12 and v[0] > 0
    # reflections in the sides: side opposite A is BC, etc.
    RA, RB, RC = reflection(V[1], V[2]), reflection(V[0], V[2]), reflection(V[0], V[1])
    for M in (RA, RB, RC):
        assert np.allclose(M.T @ J @ M, J, atol=1e-12)
    for k, (M1, M2) in zip(pqr, ((RB, RC), (RA, RC), (RA, RB))):
        P = M1 @ M2
        Pk = np.linalg.matrix_power(P, k)
        assert np.allclose(Pk, np.eye(3), atol=1e-9)
        assert all(not np.allclose(np.linalg.matrix_power(P, j), np.eye(3), atol=1e-6) for j in range(1, k))
    area = np.pi * (1 - sum(1 / m for m in pqr))
    tiles = [(tuple(V), 0)]
    keys = {key(V)}
    i = 0
    while i < len(tiles):
        tri, par = tiles[i]
        i += 1
        for a, b in ((0, 1), (1, 2), (2, 0)):
            M = reflection(tri[a], tri[b])
            new = tuple(M @ v for v in tri)
            k = key(new)
            if k in keys or max(np.arccosh(max(v[0], 1.0)) for v in new) > D_MAX:
                continue
            keys.add(k)
            tiles.append((new, 1 - par))
    for tri, _ in tiles:
        angs = sorted(angle_at(tri[j], tri[(j + 1) % 3], tri[(j + 2) % 3]) for j in range(3))
        assert np.allclose(angs, sorted(np.pi / m for m in pqr), atol=1e-7)
        assert abs(np.pi - sum(angs) - area) < 1e-7
    mirror = tuple(RC @ v for v in V)            # T reflected in its side AB
    assert covers(tiles), pqr
    return tiles, tuple(V), mirror


def covers(tiles, n=4000, seed=7):
    """Every one of n random points of the cap (uniform in hyperbolic area) lies in some tile:
    x is in the tile iff, for each side, <x, n_side> has the sign of the opposite vertex."""
    rng = np.random.default_rng(seed)
    u = rng.random(n)
    rho = np.arccosh(1 + u * (np.cosh(D_RIM) - 1))
    th = rng.random(n) * 2 * np.pi
    X = np.stack([np.cosh(rho), np.sinh(rho) * np.cos(th), np.sinh(rho) * np.sin(th)], -1)
    inside = np.zeros(n, bool)
    for tri, _ in tiles:
        ok = np.ones(n, bool)
        for a, b, c in ((0, 1, 2), (1, 2, 0), (2, 0, 1)):
            nrm = J @ np.cross(tri[a], tri[b])
            ok &= (X @ J @ nrm) * mink(tri[c], nrm) >= -1e-12
        inside |= ok
    return bool(inside.all())


def key(tri):
    """Tile identity: its centroid in Poincare-disk coordinates (bounded), rounded."""
    c = sum(tri)
    c = c / np.sqrt(-mink(c, c))
    return tuple(np.round(c[1:] / (1 + c[0]), 8))


def geodesic(u, v, n=24):
    s = np.linspace(0, 1, n)[:, None]
    w = (1 - s) * u + s * v
    return w / np.sqrt(-(-w[:, 0] ** 2 + w[:, 1] ** 2 + w[:, 2] ** 2))[:, None]


def project(P):
    el, az = np.radians(VIEW["elev_deg"]), np.radians(VIEW["azim_deg"])
    x1 = P[..., 1] * np.cos(az) - P[..., 2] * np.sin(az)
    x2 = P[..., 1] * np.sin(az) + P[..., 2] * np.cos(az)
    X = x1
    Y = P[..., 0] * np.cos(el) + x2 * np.sin(el)
    depth = P[..., 0] * np.sin(el) - x2 * np.cos(el)
    return X, Y, depth


def outline(tri):
    return np.vstack([geodesic(tri[j], tri[(j + 1) % 3])[:-1] for j in range(3)])


def rim():
    th = np.linspace(0, 2 * np.pi, 721)
    P = np.stack([np.full_like(th, np.cosh(D_RIM)), np.sinh(D_RIM) * np.cos(th), np.sinh(D_RIM) * np.sin(th)], -1)
    X, Y, _ = project(P)
    return X, Y


def panel(ax, tiles, fund, mirror, hue):
    from matplotlib.patches import Polygon
    assert VIEW["elev_deg"] > 45          # steeper than the sheet (slope < 45 deg): projection one-to-one
    RX, RY = rim()
    clip = Polygon(np.c_[RX, RY], closed=True, facecolor="none", edgecolor="none")
    ax.add_patch(clip)
    items = []
    fk, mk = key(fund), key(mirror)
    for tri, par in tiles:
        P = outline(tri)
        X, Y, dep = project(P)
        k = key(tri)
        if k == fk:
            face, edge, lw, z = hue, fs.GREY["ink"], fs.LW["thin"], 1
        elif k == mk:
            face, edge, lw, z = fs.tint(hue), fs.GREY["ink"], fs.LW["thin"], 1
        else:
            face, edge, lw, z = ((1, 1, 1) if par == 0 else fs.GREY["faint"]), fs.GREY["mid"], fs.LW["hair"], 0
        items.append((dep.mean(), X, Y, face, edge, lw, z))
    for _, X, Y, face, edge, lw, z in sorted(items, key=lambda it: (it[6], it[0])):
        for patch in ax.fill(X, Y, facecolor=face, edgecolor=edge, linewidth=lw, joinstyle="round"):
            patch.set_clip_path(clip)
    ax.plot(RX, RY, color=fs.GREY["ink"], lw=fs.LW["thin"])
    ax.set_xlim(RX.min() * 1.02, RX.max() * 1.02)
    ax.set_aspect("equal")
    ax.set_axis_off()


def data():
    out = {}
    for pqr in ((2, 8, 8), (3, 3, 12)):
        tiles, fund, mirror = tiling(pqr)
        assert key(mirror) in {key(t) for t, _ in tiles}
        far = max(np.arccosh(v[0]) for v in fund + mirror)
        assert far + 0.2 < D_RIM, (pqr, far)            # the whole pillow lies inside the drawn cap
        out[pqr] = (tiles, fund, mirror)
    return out


def draw(d):
    fs.use()
    fig = fs.figure(64)
    for i, (pqr, sig) in enumerate((((2, 8, 8), "2,8,8"), ((3, 3, 12), "3,3,12"))):
        ax = fig.add_axes([0.02 + 0.5 * i, 0.02, 0.46, 0.92])
        panel(ax, *d[pqr], fs.PILLOW[sig])
        fs.letter_at(fig, 0.005 + 0.5 * i, 0.99, "ab"[i])
    RX, RY = rim()
    for ax in fig.axes:                          # one scale for both panels: the same cap
        ax.set_xlim(RX.min() * 1.02, RX.max() * 1.02)
        ax.set_ylim(min(RY.min(), project(np.array([1.0, 0, 0]))[1]) - 0.3, RY.max() + 0.3)
    return fig


if __name__ == "__main__":
    d = data()
    for pqr, (tiles, _, _) in d.items():
        print(f"F2: {pqr}: {len(tiles)} tiles within distance {D_MAX}")
    if not check_only():
        finish(draw(d), "F2")
    print("F2: assertions passed")
