"""Generate STATEMENTS.md: every new statement of theory/eigen verbatim (no proofs), the definitions
they need, and the verbatim statements of the manuscript results they use.  Re-run after editing
any .tex fragment; the output is committed."""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
MS = os.path.join(HERE, "..", "..", "paper", "jga", "manuscript.tex")
SUPP = os.path.join(HERE, "..", "..", "paper", "jga", "supplement.tex")


def read(f):
    return open(os.path.join(HERE, f)).read()


def env(src, label):
    m = re.search(r'\\begin\{(\w+)\}(\[[^\]]*\])?\\label\{%s\}(?:\\label\{[^}]*\})*(.*?)\\end\{\1\}' % re.escape(label), src, re.S)
    assert m, label
    kind, title, body = m.group(1), (m.group(2) or ""), m.group(3)
    return f"**{kind.capitalize()} {title.strip('[]')}** (`{label}`)\n\n{body.strip()}\n"


def between(src, start, end):
    i = src.index(start)
    j = src.index(end, i + len(start)) if end else len(src)
    return src[i:j].strip() + "\n"


def main():
    ms = open(MS).read()
    D, C, R, E, N, L = (read(f) for f in ("diameter.tex", "counting.tex", "remainder.tex", "theorem_e.tex",
                                          "necessity.tex", "locality.tex"))
    out = []
    out.append("""# STATEMENTS: theory/eigen

Every new result of `theory/eigen`, verbatim from the LaTeX fragments, with its hypotheses and the
definitions it needs, and no proofs. Section A reproduces, verbatim, the statements of the results
of `paper/jga/manuscript.tex` that the new results use. Section B lists the other external inputs.
Generated by `make_statements.py`. This is the post-audit version; the version the blind reviewers
saw is the one of commit b7c3ebf.

Notation (manuscript §1–2): $\\cZ_\\Orb(t)=\\operatorname{tr}e^{-t\\Delta}\\sim\\sum_{j\\ge1}c_j(\\Orb)t^{j-2}$;
$\\sigma(\\Orb)=(g;m_1,\\dots,m_n)$ is the signature; $H_k=(c_1,\\dots,c_k)$; $\\Sig$ is the class of closed
orientable hyperbolic $2$-orbifolds whose singular points are cone points; $R=\\sum_i1/m_i$,
$P_k=\\sum_im_i^k$; $\\psi_k(x)=x^{2k-1}-x^{-1}$, $\\Psi_k(m)=\\sum_i\\psi_k(m_i)$, $C_l(m)=\\sum_ib_l(m_i)$;
$\\theta_j=\\pi j/m$; $\\Phi_m(u)=\\sum_{j=1}^{m-1}(4m\\sin\\theta_j\\sin(\\theta_j-u))^{-1}$;
$h_t(r)=e^{-t(1/4+r^2)}$, $g_t(u)=e^{-t/4}e^{-u^2/4t}/\\sqrt{4\\pi t}$; the systole $\\ell$ is the least
translation length of a hyperbolic element of $\\Gamma$, and $\\diam$ the diameter. The Laplacian is
nonnegative, with eigenvalues $0=\\lambda_0\\le\\lambda_1\\le\\cdots$ counted with multiplicity.

## A. Results of the manuscript used (verbatim statements)

""")
    out.append(between(ms, r"\begin{definition}[Signature]", r"\end{definition}") + "\\end{definition}\n")
    for lab in ("thm:IEH", "lem:counting", "lem:hypbound", "lem:Phi", "prop:heatinput", "lem:conepoly",
                "lem:triangular", "lem:sigdata", "thm:sigsep", "cor:sigarea", "thm:quantlocality"):
        out.append(env(ms, lab))
    supp = open(SUPP).read()
    out.append("Also used: the derivation of Proposition 2.7 (`prop:heatinput`) from Theorem 2.3 in the supplement, "
               "Section `sec:derivation`, quoted verbatim (`\\pref` refers to the paper):\n\n"
               + between(supp, r"For $0<a<2\pi$ let $F_a(r)", r"multiplying by $e^{-t/4}") + "\n")
    out.append("""## B. Other external inputs

1. **Plane hyperbolic trigonometry**: (H1)–(H3) of Group 1 below; the identity
   $\\operatorname{tr}[\\gamma,\\beta]-2=4\\sinh^2\\frac L2\\sin^2\\frac\\phi2\\cosh^2r$ for $\\gamma$ hyperbolic
   with translation length $L$ and $\\beta$ a rotation by $\\phi$ about a point at distance $r$ from
   the axis of $\\gamma$; and, for lines with Minkowski unit normals $n_1,n_2$ in the hyperboloid
   model, that they meet at angle $\\phi$ with $\\cos\\phi=|\\langle n_1,n_2\\rangle|$ when this is $<1$.
2. **Jørgensen's inequality** (T. Jørgensen, Amer. J. Math. 98 (1976) 739–749; statement as fetched
   in `sources/wiki_jorgensen.txt`, primary source unreachable): if $A,B$ generate a non-elementary
   discrete subgroup of $SL(2,\\mathbb C)$, then $|\\operatorname{tr}^2A-4|+|\\operatorname{tr}(ABA^{-1}B^{-1})-2|\\ge1$.
3. **Min–max** for the Laplacian of a closed orbifold: $\\lambda_j=\\min_V\\max_{0\\ne f\\in V}\\int|\\nabla f|^2/\\int f^2$
   over $(j+1)$-dimensional subspaces $V\\subset H^1$.
4. Classical: Euler's beta integral, Bernoulli numbers ($\\operatorname{sgn}B_{2n}=(-1)^{n+1}$),
   Fermat's little theorem.

## C. New results

### Group 1: diameter and counting (`diameter.tex`, `counting.tex`)

""")
    out.append(between(D, r"For $A>0$, $\varepsilon>0$ and an integer", r"\begin{lemma}[Cone points"))
    for lab in ("eig:sep", "eig:balls", "eig:diam", "eig:233"):
        out.append(env(D, lab))
    out.append("Write $0=\\lambda_0<\\lambda_1\\le\\lambda_2\\le\\dots$ for the eigenvalues of $\\Orb$, "
               "$\\mathcal N_\\Orb(x)=\\#\\{j:\\lambda_j\\le x\\}$, and $\\mathrm I,\\mathrm E_m,\\Hyp$ for the terms of "
               "Theorem 2.3 (`thm:IEH`).\n\n")
    for lab in ("eig:elem", "eig:counttail", "eig:hypall", "eig:count"):
        out.append(env(C, lab))
    out.append("\n### Group 2: remainders (`remainder.tex`)\n\n")
    out.append(between(R, r"Both expansions are nevertheless", r"\begin{proposition}[Remainder of the cone"))
    for lab in ("eig:remcone", "eig:remarea"):
        out.append(env(R, lab))
    out.append(between(R, r"For a signature $\sigma=(g;m_1,\dots,m_n)$ put $G_\sigma", None))
    out.append("\n### Group 3: Theorem E (`theorem_e.tex`)\n\n")
    out.append(between(E, r"Let $\Sig(A,M)$ be the set", r"\begin{lemma}[Integrality"))
    out.append(env(E, "eig:int"))
    out.append(between(E, r"Put $\delta_1=1/(2L_M)$", r"\begin{lemma}[The gap]"))
    out.append(env(E, "eig:gap"))
    out.append(env(E, "eig:E"))
    out.append(env(E, "eig:Mneeded"))
    out.append("\n### Group 4: necessity (`necessity.tex`)\n\n")
    out.append(between(N, r"We use the min--max principle", r"\begin{proposition}[Unbounded"))
    out.append(env(N, "eig:N1"))
    out.append(between(N, r"\paragraph{Small systole.}", r"\begin{proposition}[Pinching]"))
    out.append(env(N, "eig:N2"))
    out.append(between(N, r"Proposition~\ref{eig:N2} does not bear", r"\paragraph{What is not proved.}"))
    out.append(between(N, r"\paragraph{What is not proved.}", None))
    out.append("\n### Group 5: locality (`locality.tex`)\n\n")
    out.append(env(L, "eig:loc"))
    open(os.path.join(HERE, "STATEMENTS.md"), "w").write("\n".join(out))


if __name__ == "__main__":
    main()
