"""Independent, unconditional 2-isogeny descent for the fibre curves.

For E : y^2 = x(x^2 + a x + b) and E' : y^2 = x(x^2 - 2a x + a^2 - 4b) (2-isogenous),
Silverman-Tate (Rational Points on Elliptic Curves, III.6) give

    2^rank = |alpha(E(Q))| * |alpha'(E'(Q))| / 4,

alpha(x,y) = x mod squares, alpha(0,0) = b.  The image of alpha lies in the phi-Selmer
group Sel = { d | b squarefree : N^2 = d M^4 + a M^2 e^2 + (b/d) e^4 is soluble in R and
every Q_p }, and similarly for alpha'.  Hence

    dim span(alpha(found points)) + dim span(alpha'(found points)) - 2
        <= rank <=  dim Sel + dim Sel' - 2,

with equality throughout when the found images fill the Selmer groups.  Every ingredient is
exact integer arithmetic plus a Hensel-type p-adic solubility test written below; nothing
depends on GRH, BSD or class-group computations.  Candidate points are taken from PARI's
ellrank / elltors (and from a small search) but every point is verified exactly on the
curve before its image is used.

Run from the repository root:
    review/audit/.venv-pari/bin/python review/audit/diophantine/check_descent.py
"""
import os
import sys
from fractions import Fraction as Fr
from itertools import product
from math import gcd, isqrt

from sympy import factorint

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from dio_common import check, finish, Fail  # noqa: E402

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "check_descent.txt")
log = []


# ------------------------------------------------------------------ p-adic tools
def vp(n, p):
    if n == 0:
        return 10 ** 9
    n = abs(n)
    k = 0
    while n % p == 0:
        n //= p
        k += 1
    return k


def unit_is_square(u, p):
    """u a p-adic unit (integer prime to p): is it a square in Z_p?"""
    if p == 2:
        return u % 8 == 1
    return pow(u % p, (p - 1) // 2, p) == 1


def poly_eval(c, x):
    r = 0
    for co in reversed(c):
        r = r * x + co
    return r


def poly_deriv(c):
    return [i * c[i] for i in range(1, len(c))]


def poly_shift(c, x0, pk):
    """coefficients of h(t) = g(x0 + pk t), c = [c0, c1, ...] low-to-high."""
    n = len(c)
    out = [0] * n
    # expand sum c_i (x0 + pk t)^i
    from math import comb
    for i, ci in enumerate(c):
        if ci == 0:
            continue
        for j in range(i + 1):
            out[j] += ci * comb(i, j) * x0 ** (i - j) * pk ** j
    return out


def soluble_Zp(g, p, x0=0, k=0, depth=0):
    """Is there x in x0 + p^k Z_p with g(x) a square in Q_p (zero allowed)?  g squarefree."""
    if depth > 60:
        raise RuntimeError("p-adic recursion too deep")
    pk = p ** k
    h = poly_shift(g, x0, pk)
    v0 = vp(h[0], p)
    if h[0] == 0:
        return True
    # Hensel: simple root nearby
    gd = poly_deriv(g)
    vd = vp(poly_eval(gd, x0), p)
    if vd < 10 ** 8 and v0 > 2 * vd and v0 - vd >= k:
        return True
    mrest = min(vp(co, p) for co in h[1:]) if any(h[1:]) else 10 ** 9
    need = 3 if p == 2 else 1
    if v0 < mrest:
        if v0 % 2 == 1:
            return False
        if mrest - v0 >= need:
            u = h[0] // p ** v0
            return unit_is_square(u, p)
    for t0 in range(p):
        if soluble_Zp(g, p, x0 + pk * t0, k + 1, depth + 1):
            return True
    return False


def quartic_locally_soluble(cf, p):
    """cf = (A, B, C): y^2 = A M^4 + B M^2 e^2 + C e^4; soluble over Q_p?"""
    A, B, C = cf
    g1 = [C, 0, B, 0, A]          # e = 1, M in Z_p:  A M^4 + B M^2 + C
    if soluble_Zp(g1, p):
        return True
    # M = 1, e in p Z_p: A + B e^2 + C e^4, e = p t
    g2 = [A, 0, B * p * p, 0, C * p ** 4]
    return soluble_Zp(g2, p)


def quartic_real_soluble(cf):
    A, B, C = cf
    if A > 0 or C > 0:
        return True
    # A<=0, C<=0: need A X^2 + B X + C >= 0 for some X >= 0
    if B <= 0:
        return False
    return B * B - 4 * A * C >= 0


def squarefree_part(n):
    s = -1 if n < 0 else 1
    for p, e in factorint(abs(n)).items():
        if e % 2:
            s *= p
    return s


def sqfree_divisors(n):
    ps = list(factorint(abs(n)).keys())
    out = []
    for sign in (1, -1):
        for mask in range(1 << len(ps)):
            d = sign
            for i, p in enumerate(ps):
                if mask >> i & 1:
                    d *= p
            out.append(d)
    return out


def selmer(a, b):
    bad = set(factorint(abs(2 * b * (a * a - 4 * b))).keys())
    sel = []
    for d in sqfree_divisors(b):
        cf = (d, a, b // d)
        ok = quartic_real_soluble(cf) and all(quartic_locally_soluble(cf, p) for p in sorted(bad))
        if ok:
            sel.append(d)
    return sorted(sel)


def f2_rank(elems):
    """dimension over F_2 of the subgroup of Q*/Q*^2 generated by squarefree ints elems."""
    primes = sorted({p for e in elems for p in factorint(abs(e))} | set())
    basis = {}
    for e in elems:
        vec = (1 if e < 0 else 0)
        for i, p in enumerate(primes):
            if abs(e) % p == 0:
                vec |= 1 << (i + 1)
        while vec:
            hb = vec.bit_length()
            if hb in basis:
                vec ^= basis[hb]
            else:
                basis[hb] = vec
                break
    return len(basis)


def is_group(sel):
    s = set(sel)
    return all(squarefree_part(x * y) in s for x in sel for y in sel)


def alpha(pt, b):
    if pt is None:
        return 1
    x, y = pt
    if x == 0:
        return squarefree_part(b)
    x = Fr(x)
    return squarefree_part(x.numerator * x.denominator)


def on_curve(pt, a, b):
    x, y = Fr(pt[0]), Fr(pt[1])
    return y * y == x * (x * x + a * x + b)


def search_points(a, b, sel, bound):
    """small search on the quartics for each Selmer d; returns points (x,y) on E."""
    pts = []
    for d in sel:
        found = False
        for e in range(1, bound + 1):
            for M in range(0, bound + 1):
                if gcd(M, e) != 1:
                    continue
                val = d * M ** 4 + a * M * M * e * e + (b // d) * e ** 4
                if val < 0:
                    continue
                N = isqrt(val)
                if N * N == val:
                    x = Fr(d * M * M, e * e)
                    y = Fr(d * M * N, e ** 3)
                    if x != 0 or True:
                        pts.append((x, y))
                        found = True
                        break
            if found:
                break
    return pts


# ------------------------------------------------------------------ curves
def model(lam):
    p, q = lam.numerator, lam.denominator
    return p * p - 6 * p * q - 3 * q * q, 16 * p * q ** 3


def pari_points(a, b):
    try:
        import cypari2
    except ImportError:
        return [], None
    pari = cypari2.Pari()
    pari.allocatemem(10 ** 9)
    E = pari.ellinit([0, a, 0, b, 0])
    rk = pari.ellrank(E, 4)
    tors = pari.elltors(E)
    pts = []
    for P in list(rk[3]) + list(tors[2]):
        if len(P) == 2:
            pts.append((Fr(str(P[0])), Fr(str(P[1]))))
    return pts, [int(rk[0]), int(rk[1])]


CURVES = [
    ("C_27/2  (base pair (1,4,4),(1,1,4))", Fr(27, 2)),
    ("C_68/5  (S=136 and S=408 fibres)", Fr(68, 5)),
    ("C_1849/120 (S=1849 fibre)", Fr(1849, 120)),
    ("C_230/21 (S=4600 fibre)", Fr(230, 21)),
    ("C_155/12 (Theorem 3 example)", Fr(155, 12)),
]

try:
    # self-test of the local machinery on a textbook case: y^2 = x^3 - x (rank 0), x(x^2 + 0x - 1)
    check(selmer(0, -1) == [-1, 1] and selmer(0, 4) == [1, 2],
          "self-test: Sel^phi(y^2=x^3-x) = {+-1}; Sel^phi'(y^2=x^3+4x) = {1,2} (rank 0, Silverman-Tate III.6)", log)
    for name, lam in CURVES:
        a, b = model(lam)
        a1, b1 = -2 * a, a * a - 4 * b
        log.append(f"--- {name}: E = [0,{a},0,{b},0], E' = [0,{a1},0,{b1},0]")
        S = selmer(a, b)
        S1 = selmer(a1, b1)
        check(is_group(S) and is_group(S1), f"Selmer sets are groups: |Sel^phi| = {len(S)}, |Sel^phi'| = {len(S1)}", log)
        log.append(f"     Sel^phi(E)  = {S}")
        log.append(f"     Sel^phi'(E') = {S1}")
        upper = f2_rank(S) + f2_rank(S1) - 2
        # points
        pE, rkE = pari_points(a, b)
        pE1, rkE1 = pari_points(a1, b1)
        pE += search_points(a, b, S, 40)
        pE1 += search_points(a1, b1, S1, 40)
        for P in pE:
            if not on_curve(P, a, b):
                raise Fail(f"bad point on E {P}")
        for P in pE1:
            if not on_curve(P, a1, b1):
                raise Fail(f"bad point on E' {P}")
        imE = {alpha(P, b) for P in pE} | {1, squarefree_part(b)}
        imE1 = {alpha(P, b1) for P in pE1} | {1, squarefree_part(b1)}
        check(imE <= set(S) and imE1 <= set(S1), "images of found points lie in the Selmer groups", log)
        lower = f2_rank(list(imE)) + f2_rank(list(imE1)) - 2
        log.append(f"     images: alpha = {sorted(imE)}, alpha' = {sorted(imE1)}")
        log.append(f"     {lower} <= rank <= {upper}   (PARI ellrank on E: {rkE}, on E': {rkE1})")
        if lower == upper:
            log.append(f"     RANK PROVEN = {lower} by 2-isogeny descent (unconditional)")
        else:
            log.append("     rank NOT closed by 2-isogeny descent alone")
        expected = {Fr(27, 2): 0, Fr(68, 5): 2, Fr(1849, 120): 3, Fr(230, 21): 3, Fr(155, 12): 2}[lam]
        check(lower <= expected <= upper, f"claimed rank {expected} within [{lower},{upper}]", log)
        if lam == Fr(27, 2):
            check(lower == upper == 0, "C_27/2 has rank 0, unconditionally (2-isogeny descent)", log)
    log.append("ALL DESCENT CHECKS PASSED")
    finish(log, OUT)
except Fail:
    finish(log, OUT)
    sys.exit(1)
